package com.example.lab4.model

val students = listOf(
    Student("1.",
        "George William",
        "Kasaazi",
        "MSIT",
        "Software Engineering",
        "II"),
    Student("2.",
        "Eric",
        "Semindu",
        "MSIT",
        "Cyber Security",
        "II"),
    Student("3.",
        "Rachel",
        "Ayateke",
        "MSIT",
        "Software Development",
        "I"),
    Student("4.",
        "Gaelle",
        "Mutoni",
        "MSEAI",
        "Machine Learning",
        "I"),
    Student("5.",
        "Benedictus",
        "Rukundo",
        "MSIT",
        "Cyber Security",
        "I"),
    Student("6.",
        "Joseph",
        "Kimbugwe",
        "MSIT",
        "Data Science",
        "II"),
    Student("7.",
        "Ester",
        "Namara",
        "MSIT",
        "Data Science",
        "II"),
    Student("8.",
        "Mastel",
        "Mahoro",
        "MSIT",
        "Machine Learning",
        "II"),
    Student("9.",
        "Brice",
        "Muvunyi",
        "MSIT",
        "Machine Learning",
        "II"),
    Student("10.",
        "Peter",
        "Owoade",
        "MSEAI",
        "Artificial Intelligence",
        "II"),
)